import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { CollapseProvider } from '@/context/CollapseContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <CollapseProvider>
      
      <body className={inter.className}>{children}</body>
      </CollapseProvider>
    </html>
  )
}
